dotnet run -m Resolve data.json "."
dotnet run -m Resolve data.json "。"
dotnet run -m Resolve data.json "/"
dotnet run -m Resolve data.json ":"
dotnet run -m Resolve data.json "@"
dotnet run -m Resolve data.json "?"
dotnet run -m Resolve data.json "\"
